comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

coverage:
  range: "70..100"
  round: down
  precision: 2
  status:
    project:
      default:
        target: 60%
        threshold: 0%

