comment:
  layout: " diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

coverage:
  range: "70..100"
  round: down
  precision: 2
  status:
    project:
      default:
        target: 30%
        threshold: 0%

