server:
  port: 8080

spring:
  application:
    name: CaseLab

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
  driver-class-name: org.postgresql.Driver

  profiles:
    active: @profileActive@
