server:
  port: 8080

spring:
  application:
    name: CaseLab

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver

  profiles:
    active: @profileActive@
