spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    name: postgres
    username: postgres
    password: postgress
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
