server:
  port: 8080

spring:
  profiles:
    active: @profileActive@
  application:
    name: CaseLab

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    driver-class-name: org.postgresql.Driver

