spring:
  datasource:
    url: jdbc:postgresql://case-lab-db:5432/
    name: ${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
