name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          
      - name: Maven Package
        run: mvn -B clean package -DskipTests
