name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
 
  push_compose:
    name: Push docker-compose.yaml to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy docker-compose.yaml via SSH
        uses: appleboy/scp-action@master
        with:
          host: 178.21.8.3
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.SSH_USER }}"
          overwrite: true
  
  build-image:
    runs-on: ubuntu-latest
    steps:
    -
     name: Checkout
     uses: actions/checkout@v3
    - 
     name: Login to hub
     uses: docker/login-action@v3
     with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
     name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3  
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: sladkkov/case-lab-java-crm:latest
     
  delete-recent-container:
     name: delete-recent-container
     runs-on: ubuntu-latest
     steps: 
       -
        name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 178.21.8.3
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |  
           docker-compose down \        
      
  deploy:
     name: deploy
     needs: [push_compose, delete-recent-container, build-image]
     runs-on: ubuntu-latest
     steps: 
       -
        name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 178.21.8.3
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: docker-compose up
