name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    -
     name: Checkout
     uses: actions/checkout@v3
    - 
     name: Login to hub
     uses: docker/login-action@v3
     with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
     name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v3  
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: sladkkov/case-lab-java-crm:latest
        
  delete-recent-container:
     runs-on: self-hosted
     needs: build_image
     steps:
     -
      name: Remove recent containers
      run: docker-compose down
     -  
      name: Remove data
      run: docker system prune -a -f
     -
      name: Update docker compose file
      run: | 
       mkdir CaseLabJavaCRM \
       cd CaseLabJavaCRM \
       curl -o docker-compose.yaml https://raw.githubusercontent.com/sladkkkov/CaseLabJavaCRM/develop/docker-compose.yaml \    
       
  deploy:
      runs-on: self-hosted 
      needs: delete-recent-container
      steps:
        - name: checkout repo
          uses: actions/checkout@v3
        - name: docker-compose
          run: docker-compose up -d
