name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'
            cache: 'maven'
        - name: Build with Maven
          run: mvn -B clean verify -Pprod --file pom.xml
        - name: Test Coverage
          uses: codecov/codecov-action@v1
          with:
           token: ${{ secrets.CODECOV_TOKEN }}
